# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

env:
  DB_ADDRESS: ${{secrets.DB_ADDRESS}}
  DB_USERNAME: ${{secrets.DB_USERNAME}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}

jobs:
  build:

    name: "빌드 하기"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven # 테스트 코드 스킵하고 jar파일 생성
      run: mvn clean package -DskipTests

    - name: Log in DockerHub #"도커 허브에 로그인"
      uses: docker/login-action@v3
      with:
        username: ${{ sercrets.DOCKERHUB_USERNAME }}
        password: ${{ sercrets.DOCKER_PASSWORD }}

    - name: "도커 이미지 빌드 및 푸쉬"
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ sercrets.DOCKER_USERNAME }}/backend:latest

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: '22'
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
